# This is a basic workflow to help you get started with Actions

name: Optimize resource pack
on:
  push:
    tags:
      - '**'
jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = '.'
            output_file_path = '/tmp/BloodStone.zip'
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/BloodStone.zip
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      - name: cd tmp
        run: cd /tmp
      - uses: actions/checkout@v4
      - name: Copy file via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "BloodStone.zip"
          target: ${{ secrets.DESTINATION }}
